# Generated by Django 4.1.1 on 2022-12-13 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_pedia', '0004_category_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=50000)),
                ('author', models.CharField(max_length=50)),
                ('video', models.FileField(blank=True, upload_to='content_videos')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_pedia.book')),
            ],
        ),
    ]
