# Generated by Django 4.1.1 on 2022-12-16 10:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_pedia', '0007_followerscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
