# Generated by Django 4.1.1 on 2022-12-17 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_pedia', '0008_alter_content_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_pedia.book'),
        ),
    ]
